// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeStore.proto

package com.adinneen.smokeStore;

public interface GamesSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeStore.GamesSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string summary = 1;</code>
   */
  java.lang.String getSummary();
  /**
   * <code>string summary = 1;</code>
   */
  com.google.protobuf.ByteString
      getSummaryBytes();
}
