// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeStore.proto

package com.adinneen.smokeStore;

public interface GameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeStore.Game)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string desc = 2;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>bool installed = 3;</code>
   */
  boolean getInstalled();
}
