// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeStore.proto

package com.adinneen.smokeStore;

public interface GamesOwnedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeStore.GamesOwned)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
