// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeStore.proto

package com.adinneen.smokeStore;

public interface ListingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeStore.ListingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameList = 1;</code>
   */
  java.lang.String getGameList();
  /**
   * <code>string gameList = 1;</code>
   */
  com.google.protobuf.ByteString
      getGameListBytes();
}
