// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeStore.proto

package com.adinneen.smokeStore;

public interface OwnedGamesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeStore.OwnedGamesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountName = 1;</code>
   */
  java.lang.String getAccountName();
  /**
   * <code>string accountName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountNameBytes();
}
