// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeStore.proto

package com.adinneen.smokeStore;

public final class SmokeStoreProto {
  private SmokeStoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeStore_StoreGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeStore_StoreGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeStore_GamesSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeStore_GamesSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeStore_StoreGame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeStore_StoreGame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020smokeStore.proto\022\nsmokeStore\" \n\020StoreG" +
      "ameRequest\022\014\n\004name\030\001 \001(\t\"\037\n\014GamesSummary" +
      "\022\017\n\007summary\030\001 \001(\t\"\'\n\tStoreGame\022\014\n\004name\030\001" +
      " \001(\t\022\014\n\004desc\030\002 \001(\t2\226\001\n\005Store\022H\n\ngetSumma" +
      "ry\022\034.smokeStore.StoreGameRequest\032\030.smoke" +
      "Store.GamesSummary\"\000(\001\022C\n\010getOwned\022\034.smo" +
      "keStore.StoreGameRequest\032\025.smokeStore.St" +
      "oreGame\"\0000\001B,\n\027com.adinneen.smokeStoreB\017" +
      "SmokeStoreProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smokeStore_StoreGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smokeStore_StoreGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeStore_StoreGameRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_smokeStore_GamesSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smokeStore_GamesSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeStore_GamesSummary_descriptor,
        new java.lang.String[] { "Summary", });
    internal_static_smokeStore_StoreGame_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smokeStore_StoreGame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeStore_StoreGame_descriptor,
        new java.lang.String[] { "Name", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
