// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeLibrary.proto

package com.adinneen.smokeLibrary;

public interface GameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeLibrary.Game)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
