// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeLibrary.proto

package com.adinneen.smokeLibrary;

public interface InstalledRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smokeLibrary.InstalledRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountName = 1;</code>
   */
  java.lang.String getAccountName();
  /**
   * <code>string accountName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountNameBytes();
}
