// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeLibrary.proto

package com.adinneen.smokeLibrary;

public final class SmokeProto {
  private SmokeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeLibrary_GameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeLibrary_GameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeLibrary_GameInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeLibrary_GameInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeLibrary_InstalledRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeLibrary_InstalledRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeLibrary_GamesInstalled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeLibrary_GamesInstalled_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022smokeLibrary.proto\022\014smokeLibrary\"\"\n\013Ga" +
      "meRequest\022\023\n\013accountName\030\001 \001(\t\"\033\n\010GameIn" +
      "fo\022\017\n\007message\030\001 \001(\t\"\'\n\020InstalledRequest\022" +
      "\023\n\013accountName\030\001 \001(\t\"!\n\016GamesInstalled\022\017" +
      "\n\007message\030\001 \001(\t2\237\001\n\007Library\022B\n\013getGameIn" +
      "fo\022\031.smokeLibrary.GameRequest\032\026.smokeLib" +
      "rary.GameInfo\"\000\022P\n\ngetInstall\022\036.smokeLib" +
      "rary.InstalledRequest\032\034.smokeLibrary.Gam" +
      "esInstalled\"\000(\0010\001B)\n\031com.adinneen.smokeL" +
      "ibraryB\nSmokeProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smokeLibrary_GameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smokeLibrary_GameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeLibrary_GameRequest_descriptor,
        new java.lang.String[] { "AccountName", });
    internal_static_smokeLibrary_GameInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smokeLibrary_GameInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeLibrary_GameInfo_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_smokeLibrary_InstalledRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smokeLibrary_InstalledRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeLibrary_InstalledRequest_descriptor,
        new java.lang.String[] { "AccountName", });
    internal_static_smokeLibrary_GamesInstalled_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smokeLibrary_GamesInstalled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeLibrary_GamesInstalled_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
