// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smokeLibrary.proto

package com.adinneen.smokeLibrary;

public final class SmokeProto {
  private SmokeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeLibrary_GameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeLibrary_GameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smokeLibrary_Game_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smokeLibrary_Game_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022smokeLibrary.proto\022\014smokeLibrary\"\033\n\013Ga" +
      "meRequest\022\014\n\004name\030\001 \001(\t\"5\n\004Game\022\014\n\004name\030" +
      "\001 \001(\t\022\014\n\004desc\030\002 \001(\t\022\021\n\tinstalled\030\003 \001(\0102\223" +
      "\001\n\007Library\022>\n\013getGameInfo\022\031.smokeLibrary" +
      ".GameRequest\032\022.smokeLibrary.Game\"\000\022H\n\021ge" +
      "tInstalledGames\022\031.smokeLibrary.GameReque" +
      "st\032\022.smokeLibrary.Game\"\000(\0010\001B)\n\031com.adin" +
      "neen.smokeLibraryB\nSmokeProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smokeLibrary_GameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smokeLibrary_GameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeLibrary_GameRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_smokeLibrary_Game_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smokeLibrary_Game_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smokeLibrary_Game_descriptor,
        new java.lang.String[] { "Name", "Desc", "Installed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
